In [1]:
import seaborn as sns 
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
sft_log_file = '../logs/sft_train_log_20231211-2250.csv'
dpo_log_file = '../logs/dpo_train_log_20231213-0214.csv'

In [3]:
sft_df = pd.read_csv(sft_log_file)
dpo_df = pd.read_csv(dpo_log_file)
sft_df.head(5)

   Unnamed: 0  epoch  learning_rate    loss  step
0           0   0.00   1.400000e-08  2.5986     1
1           1   0.00   1.400000e-06  2.6353   100
2           2   0.01   2.800000e-06  2.4905   200
3           3   0.01   4.200000e-06  2.3610   300
4           4   0.01   5.600000e-06  2.2837   400

In [ ]:
# plt.title('learning_rate')
sns.lineplot(
    x="step", 
    y="learning_rate", 
    data=sft_df,
    )

In [ ]:
plt.title('sft loss')
sns.lineplot(
    x="step", 
    y="loss", 
    color='dodgerblue',
    data=sft_df,
    )
plt.savefig('../img/sft_loss.png')

In [4]:
dpo_df.head(5)

,Unnamed: 0,epoch,learning_rate,logits/chosen,logits/rejected,logps/chosen,logps/rejected,loss,rewards/accuracies,rewards/chosen,rewards/margins,rewards/rejected,step
0,0,0.00,1.000000e-08,-3.525447,-3.550683,-256.702698,-143.308243,0.7689,0.437500,-0.044875,-0.072844,0.027969,1
1,1,0.01,2.000000e-07,-3.509013,-3.557282,-270.281708,-150.850433,0.7438,0.486842,0.002034,-0.020194,0.022228,20
2,2,0.01,4.000000e-07,-3.509622,-3.544898,-286.783966,-162.946915,0.7038,0.529688,0.024229,0.046643,-0.022414,40
3,3,0.02,6.000000e-07,-3.521220,-3.554179,-267.424896,-151.984573,0.7218,0.507812,0.004973,0.008775,-0.003803,60
4,4,0.03,8.000000e-07,-3.513215,-3.551011,-281.538208,-157.784546,0.6995,0.548437,0.057179,0.069537,-0.012358,80

In [ ]:
plt.title('dpo loss')
sns.lineplot(
    x="step", 
    y="loss", 
    color='orange',
    data=dpo_df[0: 6000 // 20],  # 只使用了到6000步的checkpoit，后面的有过拟合迹象
    )
plt.savefig('../img/dpo_loss.png')

In [1]:
import torch
import sys, os
root = os.path.realpath('.').replace('\\','/').split('/')[0: -1]
root = '/'.join(root)
sys.path.append(root)

from model.infer import ChatBot
from config import InferConfig

bot = ChatBot(InferConfig())
model = bot.model

In [2]:
param_size = sum([p.numel() for p in model.parameters()]) / 1000 / 1000
print('model parameters size: {:.2f} M = {:.2f}B'.format( param_size , param_size / 1000))

print('GPU memory used: {:.2f}GB'.format(torch.cuda.memory_allocated() / (1024 ** 3)))

model parameters size: 210.19 M = 0.21B
GPU memory used: 0.40GB